### ISSUE TITLE
Create legend in the sankey diagrams

### ISSUE THREAD

**Issue by cezar77** [ilri/livegene#50]
For both sankey diagrams (_AwardedBudget_ and _StaffRoles_) a legend would be appropriate to describe the node types.

The ongoing solution is good, but maybe we could take a more sophisticated approach.

How about creating an array to hold both colours and labels for the nodes, for example:

    nodeTypes: [
        person: {
            colour: 'red',
            label: 'Staff member',
        },
        pi: {
            colour: 'yellow',
            label: 'Principal investigator',
        },
    }

There is some overhead in this approach, but it offers more flexibility in defining the labels.

**Comment by jbenndorf** [comment]
I have pushed a commit for this enhancement, is this what you had in mind? 

On a similar note, I was wondering whether the current size/ position of the legend is satisfactory. If the legend includes 'Principle Investigator' instead of 'PI', there might be a chance of this overlapping with the chart labels. I could decrease the font size of the legend or increase the chart margins for more space for the legend. 

Alternatively, I could take the legend out of the chart altogether and place it in a separate container. This would be similar to the World Map container approach. What do you think?
